INSERT INTO CUSTOMER(CUST_NAME, CREATED_DATE) VALUES ('Akhil Jain', current_date);
INSERT INTO CUSTOMER(CUST_NAME, CREATED_DATE) VALUES ('Ankit Goyal', current_date);

INSERT INTO BANK (BANK_CODE, BANK_NAME, CREATED_DATE) VALUES ('1111','BANK1111', current_date);
INSERT INTO BANK (BANK_CODE, BANK_NAME, CREATED_DATE) VALUES ('2222','BANK2222', current_date);

INSERT INTO PAYEE (PAYEE_NAME, IBAN, BANK_CODE, CUST_ID, CREATED_DT, LAST_MODIFIED_DT) VALUES ('PAYEE101', 'IBAN101', '1111', 1, current_date, current_date);
INSERT INTO PAYEE (PAYEE_NAME, IBAN, BANK_CODE, CUST_ID, CREATED_DT, LAST_MODIFIED_DT) VALUES ('PAYEE102', 'IBAN102', '2222', 2, current_date, current_date);