CREATE TABLE CUSTOMER(
	CUST_ID bigint AUTO_INCREMENT PRIMARY KEY,
	CUST_NAME VARCHAR(50) NOT NULL,
	CREATED_DATE date	
);

CREATE TABLE BANK(
	BANK_CODE VARCHAR(4) PRIMARY KEY,
	BANK_NAME VARCHAR(50) NOT NULL,
	CREATED_DATE date	
);

CREATE TABLE PAYEE(
	PAYEE_ID bigint AUTO_INCREMENT PRIMARY KEY,
	PAYEE_NAME VARCHAR(50),
	IBAN VARCHAR(20),
	BANK_CODE VARCHAR(4),
	CUST_ID bigint(20),
	CREATED_DT date,
	LAST_MODIFIED_DT date,
	CONSTRAINT FK_CUST_ID_ID FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
	CONSTRAINT FK_BANK_CODE FOREIGN KEY (BANK_CODE) REFERENCES BANK(BANK_CODE)	
);